name: Qodana

on:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "highest"
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
